
details_content_info = '/html/body/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div'  # 'Em contrução'
address_info_value_xpath = '/html/body/div[2]/div[1]/div[1]/div[1]/div[5]/div[1]/p'
neighborhood    = '/html/body/div[2]/div[1]/div[1]/div[1]/div[2]/div/nav/ol/li[4]/a'
private_area    = '/html/body/div[2]/div[1]/div[1]/div[1]/div[4]/div/div/div/p[1]/span[2]'
bedroom         = '/html/body/div[2]/div[1]/div[1]/div[1]/div[4]/div/div/div/p[2]/span[2]'
bathroom        = '/html/body/div[2]/div[1]/div[1]/div[1]/div[4]/div/div/div/p[3]/span[2]'
garage          = '/html/body/div[2]/div[1]/div[1]/div[1]/div[4]/div/div/div/p[4]/span[2]'
floor           = '/html/body/div[2]/div[1]/div[1]/div[1]/div[4]/div/div/div/p[5]/span[2]'
balcony         = '/html/body/div[2]/div[1]/div[1]/div[1]/div[4]/div/div/div/p[6]/span[2]'
condo_fee_price = '//*[@id="condo-fee-price"]'
IPTU_price      = '//*[@id="iptu-price"]'
price           = '/html/body/div[2]/div[1]/div[1]/div[1]/div[3]/div/div[1]/div[1]/p[2]'
url             = ''
building_name   = ''
suite           = ''
closet          = ''
toilet          = ''
service_area    = ''
dependence_maid = ''
pool            = ''
party_room      = ''
sports_court    = ''
playground      = ''
gym             = ''
